[package]
name = "lambda-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.16"
gorf-gen-macro = {path="../gorf-gen-macro"}
