[package]
name = "rave"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
iced-x86.workspace = true
id-arena.workspace = true
rat-ir = { version = "0.1.0", path = "../../ratpack/rat-ir" }
rayon = "1.10.0"
